[package]
name = "multitask"
version = "0.41.1"
authors = ["Aram Drevekenin <aram@poor.dev>", "Carl Leake <leakec57@gmail.com"]
edition = "2018"
rust-version = "1.60"

[dependencies]
zellij-tile = "0.41.1"
