[package]
name = "multitask"
version = "0.42.2"
authors = ["Aram Drevekenin <aram@poor.dev>", "Carl Leake <leakec57@gmail.com"]
edition = "2018"
rust-version = "1.84"

[dependencies]
zellij-tile = "0.42.2"
